.github/ISSUE_TEMPLATE/feature_request.md

chore: issue template추가

---

src/drawer/components/Category/Category.style.ts
src/drawer/components/Category/Category.tsx

- 서랍장에 사용되는 카테고리 유형 컴포넌트를 제작했습니다.
- resolved #11 
- 카테고리 리스트를 같은 파일 안에 작성하긴 했는데 따로 빼는게 나을까요?
- isSelected가 안되었을 때 color가 피그마에 있는 color보다 좀 연한거 같더라구요..? 한 번 디자인팀에 체크를 해봐야할 것 같습니당

feat: 카테고리 유형 컴포넌트 제작 (#11)

---

package.json
yarn.lock

- YDS 버전 업그레이드
작은 일이라서 이슈 안 파고 브랜치명에 이슈 번호도 안 넣었습니당
버전업 야호야호
브랜치 이름에 오타 불편해도 넘어가주세요..................................
스토리북 문서 확인하면서 작업하시면 도움이 될 거 같습닌다
[스토리북 문서 짜잔](https://yds-react-storybook.s3.ap-northeast-2.amazonaws.com/1.0.0/index.html?path=/docs/foundation-usage-guide--docs)

chore: upgrade @yourssu/design-system-react

---

package.json
yarn.lock

- resolved #42 
- yarn add react-hook-form
- yarn add use-debounce

chore: react-hook-form / use-debounce 도입

---

src/drawer/pages/ServiceDetail/ServiceDetail.style.ts
src/drawer/pages/ServiceDetail/ServiceDetail.tsx

- resolved #50 
- 서랍장 상세 페이지 상단 화면 디자인 수정 반영
- `Title` 텍스트 폰트 크기 변경
- `Developer` 텍스트 색상 변경
- 서랍장 상세 페이지 Recommend 버튼 색상 변경
없음
많음

style: 서랍장 상세 화면 디자인 수정

---

src/home/components/Notification/Notification.style.ts
src/home/components/Notification/Notification.tsx
src/home/hooks/useInterval.ts
src/home/pages/Home.style.ts
src/home/pages/Home.tsx
src/hooks/useInterval.ts

- Home 화면의 공지 컴포넌트를 구현했습니다.
- resolved #45 
- Dummy라고 되어 있는 것들은 확인을 위해 넣어둔 더미데이터 입니다! API 연결할 때 삭제할 예정입니다.
- `Notification.style.ts`에 있는 `#e7ecf6`은 YDS에 없는 색상이라 헥스코드로 넣었습니다.
- `Notification`에서 자동 슬라이드 구현을 위해 `document.getElementById`를 이용해서 구현했는데 이 방법이 괜찮은지 여쭤보고 싶습니다..!
- styled-component 내에서 transition이나 keyframes을 이용한 animation으로 시도해봤다가 공지글이 바뀌는 과정에서 깜빡임을 해결하지 못해서 현재 방법으로 구현했습니다.
- API가 완성되면 더미데이터를 지우고 API를 연결해야 합니다.
- [이 글](https://velog.io/@goldbear2022/setInterval-%ED%8A%B9%EC%A7%95%EA%B3%BC-useInterval)을 보고 `setInterval`이 아닌 `useInterval`를 사용하는 것이 좋을 것 같다고 판단해서 `useInterval` 훅을 추가했습니다.
- 한나가 DOM을 직접 조작하는 것은 좋지 않다고 해서 useRef를 이용한 다른 방법으로 구현했습니다!
- 한 가지 문제점이 있는데 저의 부족한 지식으로는 해결하지 못했습니다ㅠ 혹시 원인과 해결방법을 아시는 분이 계실까용..
- `StyledNotificationArray`라는 스타일 컴포넌트를 통해서 스타일을 지정해주는 방식으로 구현했는데, 공지 …

feat: Home 화면 공지 컴포넌트 구현

---

src/drawer/components/CategoryWithoutAll/CategoryWithoutAll.style.ts
src/drawer/components/Input/Input.style.ts
src/drawer/components/TextArea/TextArea.style.ts
src/drawer/constants/mobileview.constant.ts

- resolved #66  (자세한 건 이슈에..~)
기존 mobile breakpoint를 30rem = 480px로 수정합니다.

feat: change mobile breakpoint

---

src/home/components/HomeLayout/HomeLayout.tsx
src/home/components/login/Login.style.ts
src/home/components/login/Login.tsx
src/home/pages/Home.tsx
src/index.css

- resolved #24  
비밀번호 컴포넌트에서 @soongsil.ac.kr이 붙어버려서 다시 수정해놨습니닷!
https://github.com/yourssu/Soomsil-Web/assets/85864699/7ed0dad1-bd0d-45c0-9036-d590cfc76c73
- Nav에서 유저의 위치가 '/'일때만 네비바가 나올 수 있게 변경해두었습니다.
- react-hook form을 통해 로그인 페이지를 퍼블리싱 해보았습니다!
- 백엔드 API관련 질문을 남겨뒀는데 아직 회신을 못받아서 API작업은 시간이 걸릴것 같아요(우선 스웨거도 안돼서ㅜㅜㅜ)
- react-cookie사용하려고 하는데 다들 괜찮으신가요?
- servicse폴더를 루트에 팠고 그 하위에 TokenService파일을 만들어서 쿠키 세팅을 할 예정입니다!

feat: 로그인 퍼블리싱

---

package.json
src/components/Card/Card.style.ts
src/components/Card/Card.tsx
src/components/Dropdown/Dropdown.tsx
src/drawer/components/Dialog/ServiceRemoveModal.style.ts
src/drawer/components/Dialog/ServiceRemoveModal.tsx
src/drawer/components/DrawerCard/UserDrawerCard/UserDrawerCard.style.ts
src/drawer/components/DrawerCard/UserDrawerCard/UserDrawerCard.tsx
src/drawer/components/Header/Header.style.ts
src/drawer/pages/ServiceDetail/ServiceDetail.tsx
yarn.lock

- resolved #76 
- `ServiceRemoveModal.tsx`
- 서비스 삭제 버튼 클릭 시 띄워지는 삭제 확인 모달을 구현했습니다. 
- `Header.tsx`
- 모달이 열렸을 때 `Header`에 Overlay가 적용이 안되는 문제가 있어 `Header`의 `z-index`를 0으로 수정하였습니다.
- `Card.tsx` (@nijuy)
- 모달을 추가하니 `Card.Setting` 컴포넌트에 선언된 `height: 100%` 속성이 정상적으로 동작하지 않아 수직 정렬 방식을 flex-box로 수정하였습니다.
- `Dropdown.tsx` (@JjungminLee)
- `Dropdown` 컴포넌트 내부에 `ref`를 전달해야 해서 `React.forwardRef`를 사용했는데 문제 생기면 알려주세요!
- 빠른 구현을 위해 [@radix-ui/react-dialog](https://www.radix-ui.com/primitives/docs/components/dialog) 라이브러리를 추가했습니다.
- PR 리뷰 반영하기

feat: 서랍장 서비스 삭제 모달 구현

---

src/home/components/SearchKeyword/SearchKeyword.tsx

- 확장자 파일 불일치에 따른 에러 수정
- .png -> .webp
- 홈 팀의 realTimeKeyword 컴포넌트에서 발생하는 확장자 에러를 수정했습니다.

fix: 확장자 수정

---

src/drawer/pages/Register/Register.tsx
src/search/hooks/useGetSearch.ts

- 배포 중 발생하는 린트 에러를 수정
- 기존 정의되어있지 않은 데이터 타입의 경우 unknown으로 수정
- 사용하지 않는 파라미터의 경우 _로 변경
- 추후 해당 부분은 담당 하시는 분이 참고 해야하될 것 같습니다!

fix: lint-error

---

vercel.json

- vercel router 적용을 시키기 위해서 vercel.json을 추가했습니다!
- vercel.json 추가

chore: 라우터 적용에 따른 vercel.json 추가

---

package.json
yarn.lock

- npm: https://www.npmjs.com/package/@yourssu/logging-system-react
- YLS 1.0.0 설치했습니다.
- event 필드 내에 모든 데이터를 넣을 수 있는 상태입니다.
- 릴리즈 노트는 살짝 천천히 써볼게요......ㅎ
Logging model version 1에 해당하는 상세 스펙에 따라 Soomsil에 model을 정립할 예정입니다.

chore: install @yourssu/logging-system-react

---

pnpm-lock.yaml

업데이트가 좀 생겨서 PR 하나 더 날려용
mac/window에 pnpm이 설치되어 있지 않으신 분이라면 설치 후 pnpm install 진행해주세요.
개발은 pnpm dev 실행하시면 됩니다.

chore: update pnpm-lock file

---

src/search/apis/getRealTimeKeyword.ts
src/search/apis/searchClient.ts
src/search/components/RealTimeKeyword/RealTimeKeyword.tsx
src/search/types/realTimeKeyword.type.ts

- resolved #120 
- endpoint를 `topQuery`에서 `topQueries`로 수정하였습니다.
- 응답 데이터 속성명을 querys에서 queries로 수정하였습니다.
- baseUrl을 환경변수로 숨기는 작업 진행하였습니다 (늦어서 죄송합니다 ㅠㅠ)
- 실시간 검색어 UI 깨지는 문제 해결하기!

fix: 실시간 검색어 api 관련 수정

---

.husky/pre-commit
package.json
pnpm-lock.yaml

chore: add husky, lint-staged, pre-commit

---

src/apis/index.ts
src/home/apis/postAuthSignIn.ts
src/home/components/DrawerRanking/DrawerRanking.tsx
src/home/pages/Login/Login.tsx
src/home/types/Auth.type.ts
src/types/Common.type.ts

- resolved #146 
수정할 게 좀 더 보여서 같이 했어용
- 환경변수 네이밍 변경
- auth client에서 설정해주는 header를 삭제합니다.
- 지금은 post만 쓰고 있긴 한데, 기본 api라 삭제해두는 게 좋다고 판단했습니다. (Ref: https://github.com/yourssu/Soomsil-Web/pull/108#discussion_r1518871316)
- Error interface 삭제 및 postAuthSignIn error type 변경
- Common Error 사용처가 postAuthSignIn밖에 없는데, AxiosError로 충분히 처리 가능할 뿐더러, 더 깔끔하다고 생각하여 제거합니다.
- error status 401 못 잡는 부분 수정했습니다.
- url 수정

fix: error type and naming

---

.github/CODEOWNERS

docs: CODEOWNERS.md 파일 업데이트

---

package.json
pnpm-lock.yaml

YDS version을 1.1.0으로 업데이트 합니다.
SuffixTextField, PasswordTextField, SearchTextField가 추가되었으며 스토리북 문서 에러가 수정되었습니다.
추가로 자잘한 수정사항들이 있으니
- https://github.com/yourssu/YDS-React/releases/tag/%40yourssu/design-system-react%401.1.0
- https://yds-react-storybook.s3.ap-northeast-2.amazonaws.com/1.1.0/index.html

chore: YDS version update

---

src/service/TokenService.ts

refactor: remove unused custom event

---

src/home/components/ChangePasswordContents/ChangePasswordFrame/ChangePasswordFrame.tsx
src/home/components/Header/Header.tsx
src/home/pages/Withdraw/Withdraw.tsx

- resolved #148 
- 없음
- `ChangePasswordFrame.tsx`, `Header.tsx`, `Withdraw.tsx`에 로고 파일 이름 변경이 반영되지 않아 반영하였습니다.
- approve 3명 되자마자 머지하기

fix: 로고 파일 이름 변경 사항이 반영되지 않았던 컴포넌트 수정

---

package.json
pnpm-lock.yaml

YDS v1.1.1이 배포되었습니다~!
@fecapark 요청하신 isMarked default value 설정, suffix type React.ReactNode로 변경, TextField 여러 개 사용 시 suffix icon 사라지는 현상
전부 해결했습니다 ^~^ 이 PR 머지되면 pull 받으셔서 바로 반영하시면 될 것 같아요
@owl1753 font loading 문제 해결했습니다
Release Note: https://github.com/yourssu/YDS-React/releases/tag/%40yourssu%2Fdesign-system-react%401.1.1
Storybook: https://yds-react-storybook.s3.ap-northeast-2.amazonaws.com/1.1.1/index.html

chore: install YDS v1.1.1

---

package.json
pnpm-lock.yaml

@fecapark 머지 후 TextField에서 ref 사용이 가능합니다
Release Note: https://github.com/yourssu/YDS-React/releases/tag/%40yourssu%2Fdesign-system-react%401.1.2

chore: update yds version (v1.1.2)

---

src/home/components/SignupContents/AgreeTerms/AgreeTerms.tsx
src/home/components/SignupContents/AgreeTerms/TermContent/CommunityTerm.tsx

- #224 
- 약관 내용 [노션](https://yourssu.notion.site/00105f8d561845608271382b13972fd7)과 동일하게 수정
- [준비중] -> [필수]
에린한테 바꿔도 된다고 확인 받았숨
- 이제 준비중인 약관이 없어서 `required` 관련 코드를 싹 걷어낼까 했는데 나중에 선택 동의 사항 같은 게 새로 생길 수도 있고.......... 해서 걍 남겨뒀습니다

fix: 회원가입 약관 중 커뮤니티 이용규칙 수정

---

src/components/ProfileDropdownMenu/ProfileDropdownMenu.tsx
src/home/components/Dialog/LogoutModal.tsx
src/home/components/Nav/Nav.tsx

- #229
- 로그아웃으로 api.logout()만 사용하던 곳
- TODO 주석으로 되어있던 곳
-> 전부 useResetUserInfo() 훅 사용하도록 수정 (쏠당신최고야)
제가 처음에 타입을 feat로 팠는데 생각해보니 refactor인 거 같아서 ^^... 
브랜치 이름도 바꾸려고 햇으나 그럼 PR 다시 열어야 하네요 그냥 한번 봐주십쇼 마음이 급했음

refactor: api.logout() -> useResetUserInfo()

---

package.json
pnpm-lock.yaml

**root 경로에 env 폴더 생성 후 `.env.production` `.env.development` 환경 분리를 진행해주셔야 합니다.**
=> url 은 슬랙으로 다시 전달 할게요
브라우저 이탈과 브라우저 새로고침 시 발생하는 이벤트가 동일한데,
브라우저 이탈 시엔 로그를 보내야 하고 브라우저 새로고침 시에는 로그를 보내지 않아야 한다는 문제점이 존재합니다.
@owl1753 제롬과 함께 고민을 해보았지만, 일단 해결책이 떠오르지 않아 ^^..
페이지 이탈 시 적재된 로그를 보내는 기능을 YLS v1.1.2에서 우선 제거합니다.

chore: update YDS version(v1.1.3), YLS version(v1.1.2)

---

.gitignore
pnpm-lock.yaml

develop 기준 lock file 변경사항이 있네요

fix: move env path

---

.github/workflows/deploy.yml

배포용 yml 추가용
깃허브 시크릿에 ~~아직 aws 키만 들어있는데 머지 전에~~ 환경변수도 추가해뒀습니다
이렇게 쓰는 거 ㄱㅊ은지 좀 봐주세요 저 알못이라 도움 필요
브랜치명에 또 오타를 ^^........ 디폴리........... 양해좀해주십시오

docs: create deploy.yml

---

package.json
pnpm-lock.yaml

- resolved #268
- @yourssu/utils 패키지를 최신 버전으로 업데이트 했습니다.
올바르지 않은 형식의 닉네임에 대해 에러 메시지를 출력합니다.
yrano에서 `hasNumberOrEnglishOrHangulOrSpace` 함수의 정규식을 서버와 일치시켰습니다. 기존 정규식은 문자열의 끝부분만 매치합니다.

fix: 회원가입 시 닉네임 검증을 하지 않는 문제

---

package.json
pnpm-lock.yaml
src/home/components/SignupContents/EmailForm/EmailForm.tsx
src/home/components/SignupContents/EmailForm/useEmailForm.ts

- resolved #270 
- `EmailForm` 내부의 `BoxButton`의 `type`을 `button`으로 변경하였습니다. 
- `@yourssu/utils` 패키지의 `isEmail` 함수를 사용하여 이메일 형식을 체크합니다.
- `BoxButton`의 `type`을 `submit`으로 설정할 시 의도치 않은 새로고침이 발생하는 문제가 있었습니다.
- '인증 메일 받기' 버튼을 누를 시 error 메시지가 변경됩니다.

fix: 이메일 형식이 올바르지 않을 시 의도치 않은 에러 메시지가 출력 되는 문제

---

src/index.css

fix: remove dark mode in `color-scheme`
