- src/drawer/components/Layout/Layout.style.ts
- src/drawer/components/Layout/Layout.tsx
- src/index.css
- src/router.tsx
- #7 
- `src/drawer/components/Layout`에 레이아웃 컴포넌트를 구현했습니다
- `router.tsx` : `Drawer`를 `DrawerLayout`으로 감쌌습니다
- `index.css` : 화면 전체 너비를 차지하도록 설정하기 위해 `#root { width: 100% }` 추가했습니다
**⚠ 화면 속 헤더와 푸터, 컨텐츠 영역의 배경색은 이해를 돕기 위해 임의로 넣은 것이며 실제 코드에 작성되어있지 않습니다**
- 레이아웃 컴포넌트의 가로가 화면 전체를 차지하게 하려고 `index.css`를 약간 만졌습니다..!
`Layout` width를 100vw로 설정해도 되긴 하는디,, 그러면 스크롤 너비를 고려해야 해서 이렇게 해봤읍니다,,🤪
- 헤더와 푸터 구현 이후 추가 확인 필요
> feat: 서랍장 레이아웃 컴포넌트 구현

- src/types/styled-components.d.ts
theme 사용 시 YDSTheme을 가져오기 위해 styled-components.d.ts 추가 후 YDSTheme을 extends 해주었습니당
- 보리와의 대화 히스토리: https://github.com/yourssu/YDS-React/pull/31
마안약 YDS 내에 정의되지 않은 컬러를 theme으로 불러오고 싶을 경우(다크모드 지원 등) DefaultTheme 타입에 추가적인 속성을 정의해주시면 됩니다.
> feat: add styled-components.d.ts

- src/drawer/components/Button/Button.style.ts
- src/drawer/components/Button/Button.tsx
- src/drawer/components/Footer/Footer.style.ts
- src/drawer/components/Footer/Footer.tsx
- src/drawer/components/Layout/Layout.tsx
- 서랍장에서 사용하는 listItem_category와 Footer를 구현했습니다.
- '더보기' 버튼과 YDS BoxButton을 제외한 버튼이 따로 없고, listItem_category 라는 이름이 뭔가 임시 네이밍(?)인 것 같은 느낌이 들어서 그냥 Button으로 네이밍했어용
- Footer는 폰트 픽스가 나중에 될 것 같다고 말씀하셔서 일단 레이아웃만 잡아뒀습니다.
- resolved #5 
아무나 #12 어프로브 플리즈....입니다............
> feat: 서랍장 Button, Footer 구현 (#5)

- src/components/Dropdown/Dropdown.style.ts
- src/components/Dropdown/Dropdown.tsx
@JjungminLee 확인 부탁드려요~!
- resolved #56 
Dropdown에서 발생하고 있는 DOM Warning을 해결하였습니다.
Dom Props 오염을 방지하기 위해 Styled Component로 전달되는 Props의 이름은 $로 시작해주세요~!
**Reference: https://styled-components.com/docs/faqs#transient-props-since-5.1 & https://styled-components.com/docs/api#transient-props**
추가로, 이러한 문제를 구별하기 쉽게 Styled Interface를 독립적으로 생성해주시면 좋을 것 같습니당
> fix: Dropdown style.ts dom warning

- src/components/Card/Card.style.ts
- src/components/Card/Card.tsx
- src/components/Card/Card.type.ts
- src/components/Dropdown/Dropdown.tsx
- src/drawer/components/DrawerCard/UserDrawerCard/UserDrawerCard.tsx
- #40
- `CardContainer`를 Link에서 div로 수정했습니다
유저가 업로드한 서비스를 보여주는 `UserDrawerCard`에 anchor 태그가 존재해서, [중첩 Link로 인한 경고가 발생](https://github.com/yourssu/Soomsil-Web/pull/34#discussion_r1493167739)하고 있었어요
- `Card` 컴포넌트 내에서 hex 값으로 주던 YDS Icon 색상을 semantic color로 수정했습니다 땡스투쭌....
- `UserDrawerCard` 설정 버튼 위치 조절을 위해 `IconContext`에 스타일 속성을 추가했습니다
<details>
<summary> 왜 스타일 컴포넌트에 css 추가하는 게 아니라 IconContext에 달았냐 </summary>
<h3>제 맘입니다</h3>
농담이고...... [이 PR](https://github.com/yourssu/Soomsil-Web/pull/34#discussion_r1493163850) 읽어보시면 **설정 버튼을 감싸던 스타일 컴포넌트에 css가 단 한 줄! 남게 된다는 걸 보실 수 있는데요**
height 정도는 IconContext에서 지정 가능한 스타일이기 때문에 한 줄짜리 스타일 컴포넌트보단 이쪽이 깔끔할 거 같았어용
</details>
- (@seocylucky) `UserDrawerCard` 내에서 상위 이벤트 전파를 막기 위해 코드를 추가했습니다 ~~오늘 체리를 너무 부르네요~~
- (@JjungminLee) `DropdownProps` 타입이 HTMLAttributes를 …
> refactor: 서랍장, Home화면 Card 컴포넌트 리팩토링

- src/drawer/components/Input/Input.style.ts
- src/drawer/components/Input/Input.tsx
- src/drawer/components/TextArea/TextArea.style.ts
- src/drawer/components/TextArea/TextArea.tsx
- src/drawer/pages/Register/Register.tsx
- resolved #41 
- 서랍장 서비스 등록 페이지에 사용되는 `TextArea` 컴포넌트를 구현했습니다.
- `Input.tsx` (@Hanna922)
- `Input` 컴포넌트의 `border-bottom`의 기본 색상을 `buttonNormal`에서 `buttonNormalPressed`로 수정했습니다. (피그마 참고)
- 지금 `Input` 컴포넌트는 `Input`의 `disabled` 속성이 `true`일 때, `border-bottom`에 `buttonDisabled` 색상을 주고 있는 상태입니다.
- 그런데 피그마를 보면 텍스트가 있을 때 입력 폼의 `border-bottom` 색상이 `buttonNormalPressed`이고 텍스트가 없을 때 `border-bottom` 색상이 `buttonDisabled`로 되어있어 개인적으로 `disabled` 속성의 차이가 아니라 입력 폼의 텍스트 유무 차이로 인해 `border-bottom` 색상이 변경되는게 맞는거 같은데 한나는 어떻게 생각하는지 궁금합니다🤔
- YDS `buttonDisabled` 색상이 잘못된 것 같아요! (https://github.com/yourssu/YDS-React/issues/40)
-  `buttonNormalPressed` - #8E9398
-  `buttonDisabled` - #B5B9BD
-  `buttonNormalPressed` - #8E9398
-  `buttonDisabled` - #8E9398
- PR 리뷰 반영하기
> feat: 서랍장 서비스 등록 페이지 TextArea 컴포넌트 구현

- src/drawer/components/Header/Header.style.ts
- src/drawer/components/Header/Header.tsx
- src/drawer/components/Header/MobileRegisterHeader.style.ts
- src/drawer/components/Header/MobileRegisterHeader.tsx
- src/drawer/components/Layout/Layout.style.ts
- src/drawer/components/Layout/Layout.tsx
- src/drawer/pages/ServiceDetail/ServiceDetail.tsx
- src/hooks/useMediaQuery.ts
- resolved #73 
- 모바일 서랍장 서비스 등록 페이지에 사용되는 `MobileRegisterHeader` 컴포넌트를 구현했습니다.
- 주어진 미디어 쿼리 문자열이 현재 화면 사이즈와 일치하는지를 반환하는 `useMediaQuery()` 커스텀 훅을 구현했습니다.
- `Layout.tsx`
- 모바일 && 서비스 등록 페이지일때 선택적으로 `MobileRegisterHeader`를 보여줄 수 있도록 수정했습니다.
- 스크롤을 내려도 헤더가 상단에 붙어있지 않는 문제 (@Hanna922)
- `Header`의 부모 요소인 `Layout` 컴포넌트에 선언된 `overflow-x: hidden` 때문에 `Header`의 `position: sticky`가 정상적으로 동작하지 않음 -> `Layout`에서 `overflow-x: hidden` 제거
- 관련 이슈 - https://github.com/w3c/csswg-drafts/issues/865
- 헤더의 `soomsil` 로고 클릭 시 `/drawer`가 아닌 `/`로 라우팅 되도록 수정했습니다. 
- PR 리뷰 반영하기
> feat: 서랍장 서비스 등록 페이지 반응형 헤더 구현

- src/drawer/components/Input/Input.style.ts
- src/drawer/components/Input/Input.tsx
- src/drawer/components/TextArea/TextArea.style.ts
- src/drawer/components/TextArea/TextArea.tsx
- src/drawer/components/WarningBox/WarningAccordion/WarningAccordion.style.ts
- src/drawer/components/WarningBox/WarningAccordion/WarningAccordion.tsx
- src/drawer/components/WarningBox/WarningBox.style.ts
- src/drawer/constants/link.constant.ts
- src/drawer/pages/Register/Register.style.ts
- src/drawer/pages/Register/Register.tsx
- resolved #68 
- 4가지 링크 별 유효성을 검증하는 로직을 추가하였습니다.
- input 내 checkValid function
- 불필요한 리렌더링을 막기 위해 useMemo 사용
- 정규식은 따로 추가하지 않고, 링크의 시작 부분만 걸어두었는데, 혹시 부족할까요....? 의견 대환영입니다~!
- '등록' 버튼 클릭 시 띄우는 validation 디자인은 react-hook-form 작업과 함께 해야할 수도 있을 것 같아서 우선 isWarned props 작업만 해두었습니다.
- @2wndrhs TextArea의 validation(warning)의 경우 label도 함께 변경되어야 해서 적용해두었습니다.
- @seocylucky WarningBox의 레이아웃을 살짝 수정하였고, WarningAccordian에 word-break를 설정했습니다.
|Web1|Web2|
|--|--|
|![image](https://github.com/yourssu/Soomsil-Web/assets/84809236/daa5c8ac-3e5e-4a1e-a696-ede167e0508d)|![image](https://github.com/yourssu/Soomsil-Web/assets/84809236/32ca115b-e1ab-4e5a-a5e9-65b15ddb55c7)|
|Mobile1|Mobile2|
|--|--|
|![image](https://github.com/yourssu/Soomsil-Web/assets/84809236/99e94878-0d07-4527-bd1a-25e1ee0ff3de)|![image](http …
> feat: 링크 유효성 검증 및 등록 페이지 레이아웃 작업

- src/drawer/components/Category/Category.tsx
- src/drawer/components/CategoryWithoutAll/CategoryWithoutAll.style.ts
- src/drawer/components/CategoryWithoutAll/CategoryWithoutAll.tsx
- src/drawer/components/WarningBox/WarningAccordion/WarningAccordion.style.ts
- src/drawer/components/WarningBox/WarningAccordion/WarningAccordion.tsx
- src/drawer/components/WarningBox/WarningBox.style.ts
- src/drawer/components/WarningBox/WarningBox.tsx
카테고리와 경고문 validation isWarned 시 작업을 했습니다.
- resolved #69 
사이드용 전체 포함 카테고리 중복 선택 못하게 수정했습니다!
서비스 등록 버튼을 누르고 나서 validation이 작동되게 하는거라 일단 다른 작업은 더 안했는데 더 필요한 부분 있을까요?!
> feat: 카테고리 및 경고문 validation isWarned 추가

- src/drawer/pages/MyDrawer/MyDrawer.tsx
- #87
그냥 `STAR`로 시작한다 무조건 선택권 그런 거 없음
1. url에서 `tab` 부분을 가져온다
2. `TabType`이 맞으면 해당 값을 `currentTab`의 초기값으로 쓴다
3. `TabType`이 아니거나 null인 경우 `STAR`를 초기값으로 쓴다
움짤에서 확인할 부분
1. 페이지 진입 시 url에 tab 값이 없으면 star로 시작
2. currentTab 바뀔 때마다 url 바뀜
3. my product 선택 상태에서 다른 페이지 갔다가 - 뒤로 가기로 돌아오면 - my product로 선택된 상태
- PR 리뷰 기반 수정
> refactor: 내 서랍장 페이지 초기 currentTab 설정 방식 수정

- src/drawer/apis/drawerClient.ts
- src/drawer/apis/getProductByProvider.ts
- src/drawer/apis/getProductDetail.ts
- src/drawer/components/MoreProductSection/MoreProductSection.style.ts
- src/drawer/components/MoreProductSection/MoreProductSection.tsx
- src/drawer/hooks/useGetProductByProvider.ts
- src/drawer/hooks/useGetProductDetail.ts
- src/drawer/pages/ServiceDetail/ServiceDetail.style.ts
- src/drawer/pages/ServiceDetail/ServiceDetail.tsx
- src/drawer/types/product.type.ts
- #107 
- `src/drawer/apis/getProductByProvider.ts` : 제작자의 서비스를 가져오는 api
- `src/drawer/apis/getProductDetail.ts` : 프로덕트 1개의 정보를 가져오는 api
- `제작자의 서비스 더보기` 내용을 `ServiceDetail` 내 별도의 컴포넌트로 분리했습니다.
- 버튼 눌렀을 때 링크는 모두 새 창에서 열립니다! 거기까지 녹화가 안되었지만... 새 창으로 열려요...............
- 더보기쪽에 제작자의 서비스가 5개 이상인 경우 **제작자의 프로덕트만 모아보는 페이지로 넘어가는 화살표**가 생겨야 하는데,
페이지 자체가 없다보니 차라리 이슈 하나 파서 진행하는 게 맞다고 생각해서 제외시켰습니다 까먹은 거 아닙니다
- 상세 페이지도 에러 처리가 안 되어있는 상황인데, 에러 처리 방향에 대한 가닥이 잡히면 반영하겠습니다..🤔
- PR 리뷰 기반 수정
> feat: 서랍장 상세 페이지 API 연결

- src/drawer/components/OverviewImage/OverviewImage.tsx
- src/drawer/components/ThumbnailInput/ThumbnailInput.tsx
- src/drawer/pages/Ranking/Ranking.tsx
소개 이미지 첨부 시, 이미지 파일만 첨부될 수 있도록 조건 추가하였습니다.
- resolved #100 
```ts
const handleFileChange = (file: File | undefined, index: number) => {
setFiles((prevFiles) => {
const newFiles = [...prevFiles];
if (file && file.type.substring(0, 5) === 'image') {
newFiles[index] = file;
} else {
alert('이미지 파일을 첨부해주세요.');
}
return newFiles;
});
};
```
이미지 파일 외의 것을 만약 사용자가 체크를 할 때, 일단 alert 처리를 하긴 했는데 괜찮을까용 함 여쭤볼까요?! 
일단 고정적으로 image류만 고를 수 있게 accept="image/*" 처리하긴 했는데 어떤 경우에는 저게 안먹는 경우도 있다고 해서 alert 처리 넣은 거긴 한데 다른 의견 있으신 분들 의견 주시면 감사하겠습니다!!!!
전에 있던 pr에 달까 했는데 최신 develop 브랜치에서 하는게 더 편할 것 같아서 그냥 새로 파서 작업했습니다ㅎㅎ
> feat: 이미지 첨부 시, 이미지 파일만 첨부될 수 있도록 조건 추가

- src/drawer/apis/getBookMarked.ts
- src/drawer/apis/getMyProduct.ts
현재 develop 브랜치에서 pull 하면 발생하는 이슈를 해결했습니다. (아래 참고)
- resolved #144 
해당 [PR](https://github.com/yourssu/Soomsil-Web/pull/129) 에서 발견하지 못한 이슈 같습니다!
drawerClient가 soomsilClient로 변경되면서 
`getBookMarked.ts`와 `getMyProduct.ts` 두 파일에 수정사항이 적용되지 않았습니다.
> fix: drawerClient -> soomsilClient 로 변경

- package.json
- resolved #141 
lint-staged에서 소스파일이 아닌 이외의 것들에(이미지와 같은 바이너리 파일) 대한 lint 검사를 하지 않도록 변경
src 하위의 {ts, tsx} 파일에 대한 검사만 실시하도록 변경했습니다.
> chore: lint-staged {ts, tsx}만 검사하도록 변경

- src/components/Fallback/Fallback.tsx
- src/drawer/pages/ServiceDetail/ServiceDetail.tsx
- #165
- 누락된 props 추가
- ServiceDetail에서 MoreProductSection을 사용할 때 providerName가 빠져있었음
- providerId -> providerName으로 변경했던 부분 중 일부가 다시 providerId로 돌아가있어서 그것도 끼워넣음
- 누락된 field 추가
- getFallbackContent()의 마지막 return문에서 `FallbackContent`의 필수 속성인 buttonText가 빠져있었음
> Fix: ServiceDetail, Fallback 컴포넌트에서 발생하는 타입 에러 수정

- src/drawer/apis/getProductByProvider.ts
- src/drawer/components/MoreProductSection/MoreProductSection.tsx
- src/drawer/hooks/useGetProductByProvider.ts
- src/drawer/pages/Provider/Provider.tsx
- src/drawer/types/product.type.ts
ProviderProductResponses 구조에 맞게 응답 타입 코드를 수정하였습니다.
- resolved #186 
ProviderProductResponses 타입 추가
```ts
export interface ProviderProductResponses {
providerName: string;
products: ProductResult[];
}
```
이에 맞게 getProductByProvider와 useGetProductByProvider를 수정하였고 상세페이지와 더보기 컴포넌트는 잘 돌아갈겁니다!
피드백 반영
> refactor: ProviderProductResponses 구조 변경 및 관련 코드 리팩토링

- src/home/components/ChangePasswordContents/CurrentPasswordForm/CurrentPasswordForm.tsx
- src/home/components/ChangePasswordContents/NewPasswordForm/NewPasswordForm.tsx
- src/home/components/SignupContents/SignupForm/SignupForm.tsx
- src/home/pages/Login/Login.tsx
#182 에서 미처 진행하지 못한 YDS 1.1.1 업데이트 내용을 진행해 주었습니다.
사실 1.1.1의 릴리즈 노트를 보면 대부분 컴포넌트 내부적 변경 사항(버그 해결)이라 
v1.1.1 로 패키지를 업데이트한 시점에서 리팩토링 할 코드는 그렇게 많지 않았습니다.
=> 자동으로 버그가 해결 됨
따라서 코드 변경사항은 `PasswordTextField`의 `isMarked` 속성의 기본 값이 지정됨에 따라,
일일이 `isMarked` 의 값을 지정해주던 코드들만 삭제했습니다.
또한, `PasswordTextField` 의 `suffix-icon` 에 대한 className 이슈를 
해결한 사항이 적용되었는지 확인하였습니다.
===> 바로 어프룹 주셔도 될듯 ?? (변경 사항이 별로 없음)
##
- resolved #191
> refactor: YDS 1.1.1 변경사항 적용

- src/home/components/Notification/Notification.tsx
- src/home/hooks/useGetAnnouncement.ts
- src/home/types/announcement.type.ts
- resolved #198 
https://github.com/yourssu/Soomsil-Web/assets/87332713/b6fc71dc-de7b-4cb4-90f6-53d9001d2d64
- Home 공지사항 API 연결
- 공지사항이 없을 때 (빈 배열일 때)
이 부분 제가 임의로 `공지사항이 없습니다.`로 정했는데 이 부분도 디자인팀과 논의를 해봐야 할까요? 
공지사항이 없을 때도 존재하는지는 어느 팀에 여쭤봐야 할까요?? ㅜㅜ 열심히 찾긴 했는데 없어서 포기했습니닷
- 로딩중 일 때
- error 일 때
- 기존에 있던 코드에서 더미 데이터를 제거하고 `useGetAnnouncement();`를 사용해 데이터를 정의(`announcements`)하여 공지사항을 보여줍니다.
- 기존에 있던 `getAnnouncement.ts`에서 공지사항 API를 호출, `useGetAnnouncement.ts`에서 불러온 데이터 캐싱하는 구조입니다.
- 전부 구현되어 있어서 타입 구현과 더미 대신 데이터로 교체만 했습니다!
> feat: Home 공지사항 API 연결

- src/home/components/ChangePasswordContents/NewPasswordForm/NewPasswordForm.tsx
- src/home/components/SignupContents/SignupForm/SignupForm.tsx
- src/hooks/useSignupFormValidator.ts
- resolved #203
- 없습니다.
- ```src/home/components/SignupContents/SignupForm/SignupForm.tsx```
- ```src/home/components/ChangePasswordContents/NewPasswordForm/NewPasswordForm.tsx```
- ```src/hooks/useSignupFormValidator.ts```
- @yourssu/utils 패키지의 ```hasNumberOrEnglishOrHangulOrSpace```, ```hasNumberAndEnglishWithSymbols```를 사용했습니다.
- 이슈에 올라와 있는 정규식의 조건과 일치합니다.
```hasNumberAndEnglishWithSymbols``` 함수에서 허용하는 특수문자는 ```! " # $ % & ' ( ) * + , - . / : ; < = > ? @ [ \ ] ^ _ \ ` { | } ~ ₩```입니다.
> fix: 비밀번호 정규식 및 코멘트 변경

- src/home/apis/postWithdraw.ts
- src/home/pages/Withdraw/Withdraw.tsx
- src/hooks/usePostWithdraw.ts
- src/hooks/useResetUserInfo.ts
- resolved #204 
- LoginState랑 UserState가 초기화 코드 누락 해결
- 로그인 했을 때
- 계정 탈퇴 후
로그아웃 `api.logout`과 LoginState를 `false`로, UserState를 `null`로 전부 초기화하는 `useResetUserInfo` 훅을 만들었습니다.
로그아웃에서도 LoginState, UserState 전부 초기화 해야하면 갖다 써도 될 것 같습니당
> fix: 회원탈퇴 후 유저정보가 남아있는 버그 수정

- src/home/components/SignupContents/EmailForm/EmailForm.tsx
- src/home/components/SignupContents/EmailForm/useEmailForm.ts
- src/home/components/SignupContents/SignupForm/SignupForm.tsx
- src/hooks/usePreventDuplicateClick.ts
- resolved #207 
```usePreventDuplicateClick``` 훅을 추가했습니다.
[참고용 블로그](https://happysisyphe.tistory.com/72)
위 블로그를 참고해서 제작했습니다.
```usePreventDuplicateClick``` 훅을 적용했습니다.
- ```src/home/components/SignupContents/EmailForm/EmailForm.tsx```
- ```src/home/components/SignupContents/SignupForm/SignupForm.tsx```
```emailSending``` state를 제거했습니다.
- ```src/home/components/SignupContents/EmailForm/useEmailForm.ts```
- 회원가입 중복 요청을 방지해 '잘못된 데이터 요청입니다.' alert가 발생하지 않습니다.
```usePreventDuplicateClick```은 ```useRef```와 ```useState```를 동시에 사용합니다. 
- ```useState```는 상태가 변경되는 즉시 반영되지 않기에 api 요청 직후 중복 호출을 막기 위해서는 ```useRef```를 사용하는 것이 안전합니다.
- ```useRef```는 re-rendering을 발생 시키지 않습니다. 따라서 버튼이 disabled 될 때 re-rendering을 발생 시키기 위해선 ```useState```를 사용해야 합니다.
Yrano react package에 ```usePreventDuplicateClick```를 추가해서 …
> fix: 회원 가입 중복 호출 방지 

- src/home/components/UserInformationCard/UserInformationCard.tsx
- #231
김뿌슝씨를 쫓아냈습니다
스웨거로 imagePK 확인하다가 갈매기 사진으로 바뀌었는데 일단 사용자는 프로필 변경 못 하게 해뒀으니 신경쓰지 마세요..!
- 스웨거에 프로필 수정 api가 존재하는데 여기서 작업 안 한 이유
프로필 이미지 / 닉네임 수정 API가 별도로 존재하는 게 아니라 하나만 있는데요,
제가 알기론 사용자가 이미지 파일을 직접 업로드 하는 게 아니라 번호만 고르는 식인 걸로 알거든요..?
(뿌슝이 이미지 N개 중 사용자가 선택 -> 그 번호를 imagePK에 넣음 -> 서버에서 imagePK에 맞는 뿌슝이 이미지를 프로필로 설정)
근데 지금 뿌슝이 이미지가 준비된 상태도 아니고, 어떻게 선택하게 할지에 대한 뷰도 없어서
일단 프로필 편집 버튼을 전부 주석처리 해뒀습니다 (혹시 제가 잘못 알고있는 거면 알려주세요)
홈 TF 채널에 프로필 이미지 관련 스레드가 있었는데 기간 지나서 안 보여요 흑흑 한번 더 물어보겠습니당...
어쨌든 김뿌슝씨 그대로 두긴 좀 그래서 일단 올립니다
> feat: `UserInformationCard`에 현재 로그인 중인 사용자 정보 넣기

- .husky/pre-commit
- .lintstagedrc
- package-lock.json
- package.json
- pnpm-lock.yaml
- resolved #243 
- `eslint` 오류가 발생하는 파일을 `staging` -> `commit`하였을 때
- `husky` `pre-commit` 스크립트 수정 (아마 이게 원인인듯)
```
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
```
- `lint-staged` 명령어를 별도 파일로 분리(`.lintstagedrc`)
- `eslint`, `prettier` 룰도 별도 파일로 관리하기 때문에 통일성을 맞춰줬습니다.
> fix: `pre-commit` 훅에서 `lint-staged` 명령이 정상적으로 동작하지 않는 버그 수정

- src/constants/email.constant.ts
- src/home/components/ResetPasswordContents/EmailInput/EmailInput.tsx
- src/home/components/ResetPasswordContents/EmailInput/useEmailInputForm.ts
- src/home/components/SignupContents/EmailForm/EmailForm.style.ts
- src/home/components/SignupContents/EmailForm/EmailForm.tsx
- src/home/pages/Login/Login.tsx
- src/home/pages/Signup/Signup.tsx
- resolved #245 
- `email.constant.ts`에 학교 메일 찾는 링크를 추가해서 전역으로 갖다 쓰게 했습니다.
- 회원가입 페이지에 `useRedirectLoggedInEffect`를 사용해 로그인 상태에서 접근을 막았습니다.
- 이전 pr에서 수정하지 못한 [훅 이름 변경](https://github.com/yourssu/Soomsil-Web/pull/233#discussion_r1652705310)을 슬쩍 같이 했습니다.
- 혹시나 궁금해하실까봐 [`rel="noopener noreferrer"`는 어떤 역할을 하는 건가요?](https://github.com/yourssu/Soomsil-Web/pull/233#discussion_r1652725446)
> feat: 회원가입 페이지에 학교 메일 찾기 링크 걸기

- src/drawer/apis/putUpdateProduct.ts
- src/drawer/components/DrawerCard/CardSettingDropdownMenu/CardSettingDropdownMenu.style.ts
- src/drawer/components/DrawerCard/CardSettingDropdownMenu/CardSettingDropdownMenu.tsx
- src/drawer/components/DrawerCard/UserDrawerCard/UserDrawerCard.tsx
- src/drawer/components/Input/Input.tsx
- src/drawer/components/OverviewImage/OverviewImage.tsx
- src/drawer/components/TextArea/TextArea.tsx
- src/drawer/components/ThumbnailInput/ThumbnailInput.tsx
- src/drawer/constants/registerFormDefaultValue.constant.ts
- src/drawer/hooks/usePutUpdateProduct.ts
- src/drawer/pages/Register/Register.tsx
- src/drawer/pages/ServiceEdit/ServiceEdit.tsx
- src/drawer/pages/ServiceEdit/useGetFilesFromURLs.ts
- src/drawer/pages/ServiceEdit/useLoadServiceDetailEffect.ts
- src/router.tsx
- resolved #235 
리뷰 환영
생각보다 난이도가 있었던 작업이었습니다..  
그리고 CORS 문제 때문에 좀 예상보다 작업 기간이 길어졌네요 죄송함다
아래 작업들을 수행했습니다.   
- 서비스 수정 라우트 제작 (`/drawer/services/<:productNo>/edit`)
- 서랍장 서비스 수정 페이지 퍼블리싱 (`<ServiceEdit />`)
- 수정 페이지 진입 시 폼 채워지는 기능 구현
- 올바르지 않은 사용자가 수정 라우트 접근 시 홈으로 리다이렉트
- `CardSettingDropDownMenu` 에 `background-color` 추가
- 서랍장 서비스 등록 및 수정 페이지에서 submit시 중복 클릭 방지 및 성공 시 navigate 기능
- 서비스 등록 성공 시: '내가 등록한 서비스' 페이지로 이동 (`/drawer/myDrawers?tab=MYDRAWER`)
- 서비스 수정 성공 시: 해당 서비스 detatil 페이지로 이동
수정 페이지 컴포넌트인 `<ServiceEdit />` 은 기본적인 로직이  
서비스 등록 페이지 컴포넌트인 `<Register />` 와 로직이 완전히 동일합니다.
서비스 등록 페이지의 폼을 그대로 가져와서   
폼에 값만 채우자고  계획했었기 때문인데요.
이 과정에서 의도치않게 폼에 존재하는 input 관련 컴포넌트들에 대하여 
아래의 리팩토링이 적용되었습니다.
- RHF를 사용하지만 input의 값을 상태로 관리하던 모든 로직 제거
- 폼에 기본 값 추가 (`registerFormDefaultValue.constant.ts`)
- 자잘한 …
> feat: 서랍장 서비스 수정 페이지 제작 및 관련 자잘한 업데이트

- src/drawer/pages/ServiceDetail/ServiceDetail.style.ts
- src/drawer/pages/ServiceDetail/ServiceDetail.tsx
- #251
- 상세 페이지 커버 이미지(?)에 대한 수정 요청이 들어와서 고쳤어요
사진 대신 어두운 컬러 단색 배경으로 수정했습니다!
사진이 들어갈 때는 프로덕트 정보 부분이 잘 안보이는 일이 있어서요 (이슈 참고)
> refactor: 서랍장 상세 페이지 배경 이미지를 삭제하고 배경 색상 추가

- src/drawer/apis/getDrawerBanner.ts
- src/drawer/hooks/useGetDrawerBanner.ts
- src/drawer/hooks/useGetNewRelease.ts
- src/drawer/hooks/useGetStarRank.ts
- src/drawer/pages/Ranking/BannerSection.tsx
- src/drawer/pages/Ranking/NewReleaseSection.tsx
- src/drawer/pages/Ranking/Ranking.style.ts
- src/drawer/pages/Ranking/Ranking.tsx
- src/drawer/pages/Ranking/RankingSection.tsx
- src/drawer/types/banner.type.ts
- resolved #234 
- `drawer/hooks/useGetDrawerBanner.ts`
- 배너 API에 요청을 보내 배너 리스트를 가져오는 쿼리입니다.
- `drawer/pages/Ranking/Ranking.tsx`
- 랭킹 페이지에서 `useGetDrawerBanner()` 쿼리를 호출하여 배너를 가져와 화면에 보여줍니다.
- 배너는 변경이 자주 일어나지 않는 데이터이기 때문에 페이지 새로고침이 이루어지지 않으면 캐시에서 배너 데이터를 가져와 보여줄 수 있도록 `useGetDrawerBanner`의 쿼리의 `staleTime`을 `Infinity`로 설정하였습니다.
- 리뷰 기반 수정
> feat: 서랍장 배너 API 연결

- src/drawer/components/Header/Header.style.ts
- src/drawer/components/TextArea/TextArea.style.ts
- resolved #254 
- `src/drawer/components/TextArea/TextArea.style.ts`
- 다크모드에서 서랍장 서비스 등록 페이지의 내용 입력 폼(`textarea`)의 배경색이 검정색으로 표시되는 문제가 있어 배경색을 흰색으로 명시하였습니다.
> fix: 서랍장 서비스 등록 페이지의 `textarea` 요소의 배경색을 흰색으로 수정

- src/search/components/ResultList/ResultListItem.style.ts
- src/search/components/ResultList/ResultListItem.tsx
- src/search/constant/index.ts
- #282
- 검색 결과에서 썸네일이 1개 이상일 때만 노출되게 함 (0개면 글만 보이게)
| 썸네일 개수 | 사진 |
|:---:|:---:|
| 0개 | ![zero](https://github.com/user-attachments/assets/36fbbf8e-69f6-40b4-8b03-55b923350504) |
| 1개~4개 | ![under 5](https://github.com/user-attachments/assets/026542f0-0677-48d7-bccc-b95682e7d895) |
| 5개 이상 | ![over 5](https://github.com/user-attachments/assets/f9222afa-c2dd-41b3-9014-395f6a850cd5) |
- 상수명 수정 (`B`가 빠져서 그거 넣음)
> fix: 검색 결과 1개에서 썸네일이 없는 경우 글만 나타나게 수정

- src/search/pages/NoResult/NoResult.style.ts
- src/search/pages/NoResult/NoResult.tsx
https://github.com/user-attachments/assets/970d44f0-dd20-4e3d-a1d4-c5833ca09b00
- resolved #281 
- `src/search/pages/NoResult/NoResult.tsx`
- 기존의 [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams)를 이용하여 Search Param을 취득하는 부분을 React Router의 [useSearchParams()](https://reactrouter.com/en/main/hooks/use-search-params) 훅을 사용하여 리팩토링 했습니다.
- 요청 및 편집 섹션을 클릭하면 링크 이동이 이루어지기 때문에 텍스트나 아이콘 네이밍에 `link`를 제거하였습니다.
- `src/search/pages/NoResult/NoResult.style.ts`
- 피그마에서 사용되던 커스텀 폰트를 같은 스타일의 YDS 폰트로 교체하였습니다.
피그마에 '검색 결과 없을 시 화면'에 네이버를 참고하라는 사항이 있어 네이버 디자인을 참고하여 카드에 마우스 호버시 카드 아래 모든 텍스트에  `underline` 효과를 주도록 하였습니다.
- 네이버 '검색 결과 없을 시 화면'
- 리뷰 반영하기
> fix: 검색 결과가 없는 경우 요청 및 편집 섹션을 클릭하면 해당 링크로 이동하도록 수정

- index.html
- public/favicon/manifest.json
파비콘 경로를 수정하였습니다. 
기존에 `favicon/apple-icon-57x57.png`와 같이 상대 경로로 설정된 것을 `/favicon/apple-icon-57x57.png` /를 앞에 추가해 수정하였습니다.
- resolved #273
[html_filepaths](https://www.w3schools.com/html/html_filepaths.asp)
> fix: favicon path에 / 추가

- src/home/components/SocialNetworkService/SocialNetworkService.tsx
`SocialNetworkService` 컴포넌트의 링크들이 새 탭이 아니라 현재 페이지에서 라우팅되는 문제를 수정했습니다.
- resolved #263
> fix: sns 버튼이 새탭으로 열리지 않는 문제 수정

- src/drawer/components/ServiceDetailContents/Carousel/Carousel.style.ts
- src/drawer/components/ServiceDetailContents/Carousel/Carousel.tsx
- src/drawer/components/ServiceDetailContents/Description/Description.tsx
- src/drawer/components/ServiceDetailContents/MoreProductSection/MoreProductSection.style.ts
- src/drawer/components/ServiceDetailContents/MoreProductSection/MoreProductSection.tsx
- src/drawer/components/ServiceDetailContents/ServiceAction/ServiceAction.tsx
- resolved #279
- resolved #274
두 이슈가 동일한 원인이라 한 브랜치에서 모두 수정했습니다
- 상세페이지의 추천 관련 워딩이 수정되었습니다
스레드에 웹팀 언급이 없어서 오늘 확인했는데! 딱 두 줄 고치는거라 그냥 여기 끼워뒀어요
[여기](https://yourssu.slack.com/archives/C06BWMEPPNV/p1724511831397999?thread_ts=1723530735.772469&channel=C06BWMEPPNV&message_ts=1724511831.397999) 보시면 됩니다
- `input type=button`을 button/Link 내에`img` 태그가 있는 형태로 수정했습니다
- `Carousel`의 화살표 버튼에 넣어놨던 `name` prop은 방향 구분을 위해 임의로 넣은 값이라,
dataset을 이용하는 게 좀 더 의도를 드러내는 거 같아서 수정했습니다
<details>
<summary>왜 버튼이 안 보였는지 적어둔 토글인데요 ^^... 사실 다 못찾았어요</summary>
<div markdown="1">
<br/>
1. `input type="button"` 요소에서 스타일 아예 안 들어가고 있었음
| localhost | build result |
|:---:|:---:|
| ![image](https://github.com/user-attachments/assets/5f9d2b01-960e-4061-bf18-a73e0eb331ed) | …
> fix: 상세페이지 이미지 버튼이 안 보이는 문제

- src/drawer/components/EmptyScreen/EmptyScreen.tsx
- #275
- 서랍장 검색 결과 없을 때
- `서비스 등록하기` 버튼 핸들러가 없어서 클릭해도 딱히 반응을 안 하고 있었음
- `handleClickButton`을 추가함
- 로그인 했으면 `서비스 등록` 페이지로 이동
- 로그인 안 했으면 다이얼로그 뜸
| 로그인 O | 로그인 X | 
|:---:|:---:|
|![logged](https://github.com/user-attachments/assets/1e19f51f-5c23-43ef-8762-7ef8a90cdb41)|![nonlogged](https://github.com/user-attachments/assets/fd25b77d-fd99-4006-92a3-fdf7bb26ff58)|
이거 원래 체리가 하기로 되어있었는데
제가 깃헙 이슈칸에 담당자 없는 것만 보고.............. 남은 작업이라 착각해서 작업한 뒤에 노션을 봐버렸어요
이제부터 노션부터 확인할게요 죄송합니다 ㅠㅠ!!!!!!!!!! @seocylucky
> fix: 서랍장 검색 결과가 없을 때 서비스 등록하기를 클릭해도 페이지가 안넘어가짐

- src/components/RealTimeKeyword/RealTimeKeyword.style.ts
- src/components/RealTimeKeyword/RealTimeKeyword.tsx
- src/search/apis/getRealTimeKeyword.ts
- src/search/hooks/useGetRealTimeKeyword.ts
- 숨쉬듯이 검색한 키워드 코드를 리팩토링하였습니다.
- `src/search/hooks/useGetRealTimeKeyword.ts`
- 불필요한 쿼리 옵션을 제거했습니다.
- `gcTIme` 옵션은 쿼리를 사용하는 컴포넌트가 모두 언마운트 되었을 때 캐시에서 제거될 때까지의 시간을 나타내지만 현재 요구사항에서는 따로 조정할 필요가 없을 것 같아서 제거하였습니다.
- `retry`, `refetchOnWindowFocus` 옵션도 쿼리의 기본값이 잘 설정되어 있고 따로 조정할 필요가 없을 것 같아 제거했습니다.
- `src/search/apis/getRealTimeKeyword.ts`
- 다른 API 호출 코드와 통일성을 맞춰 해당 함수에서 `response.data`를 반환하도록 수정하였습니다.
- Axios에서 실패한 HTTP 요청에 대해 자동으로 에러를 던져주기 때문에(`fetch`는 자동으로 안 던져줌) `try catch` 문은 제거하였습니다.
- 리뷰 받고 수정하기
> refactor: 숨쉬듯이 검색한 키워드 코드 리팩토링

- src/search/pages/NoResult/NoResult.style.ts
- src/search/pages/NoResult/NoResult.tsx
- 줄바꿈 스타일을 추가했습니다. (8/28 오후 8시 수정했습니당)
> 생각해보니까 멘트를 검색어 아래로 내리는 게 보기 더 좋을 것 같네요
라는 제롬의 의견 반영하였습니다.
- `StyledNoResultKeyword`
- `word-break: break-all;` + `overflow-wrap: break-word;`
- 검색어가 길어도 컨테이너를 넘지 않도록 단어를 중간에서 끊어주는 역할
- `StyledNoResultDescription` 
- `display: inline;` + `white-space: nowrap;`
-  inline을 해줘서 글자 수가 적을 때는 한 줄에 나오도록 + ‘에 대한 검색결과가 없습니다.’ 자체는 줄바꿈이 안되게 유지
- `div`
- 두 개를 묶어줘야 하더라구여,,,
- resolved #277 
- 너무... 달랑 넣은 것 같아서 참고를 [조금](https://smartstudio.tech/deepdive-linebreak-css-about-language/) 해봤습니다... 이렇다네요...
> fix: 검색어가 너무 길면 줄바꿈 안 되는 문제

- src/drawer/pages/Register/Register.tsx
- resolved #272 
서비스 등록 시, `내 서랍장의 Stars가 아닌 My Products로 이동`할 수 있게 하였습니다.
> fix: 서랍장 서비스 등록 시, 리다이렉트 URL myproduct로 이동

- src/home/components/MyMenuList/MyMenuList.tsx
- third-party-licenses.txt
- #269 
- `오픈소스 사용정보` 메뉴를 삭제했습니다
- 웹 사이트 내에 사용한 라이브러리 정보를 싹 명시하는 사례를 못 찾아서 메뉴 자체를 뺐는데요..............................
반대 환영합니다 어서오세요
저는 명시를 해야 한다면 저장소에 license 파일을 올려두는 것도 방법일 거 같아요
(`license-checker`나 `generate-license-file` 쓰면 만드는 건 어렵지 않을 거 같습니다. 아래 표도 같이 봐주세욥)
패키지 개발이 아니라 서비스 만들면서 라이선스 명시에 대한 생각을 깊게 해본 적이 없어서 아직 좀 헷갈리는데 🤨
어느 쪽이 좋을지 꼭 의견 주시면 감사하겠습니다~~!
| license-checker로 만들 경우 (JSON) | generate-license-file로 만들 경우 (txt) |
|:---:|:---:|
|![image](https://github.com/user-attachments/assets/8446a4ca-58c4-4b63-94af-1919bfec8dda)|![image](https://github.com/user-attachments/assets/b086f3f4-f070-4f2c-bd40-e6a6f9aee574)|
| 이름, 깃허브 주소, 라이선스 종류 | 이름, 라이선스 텍스트 |
> remove: `MyMenuList`의 오픈소스 사용정보 메뉴 삭제

- src/drawer/components/Footer/Footer.tsx
- resolved #265 
```ts
<StyledFooterText>Version 1.0.0</StyledFooterText>
```
드디어 푸터에 n.n.n을 없앴습니다.
> fix: version 1.0.0 으로 푸터 텍스트 수정

- src/drawer/components/EmptyScreen/EmptyScreen.tsx
- src/drawer/constants/empty.constant.ts
- src/drawer/pages/NewRelease/NewRelease.tsx
- src/drawer/pages/Provider/Provider.tsx
- src/drawer/pages/StarRanking/StarRanking.tsx
- src/drawer/types/emptyState.type.ts
- resolved #278 
StarRanking과 NewRelease에 카테고리별 서비스가 하나도 없을 시 나타내는 emptyscreen 관련 코드를 추가하였습니다.
피그마에 해당 카테고리가 없을 때 나타나는 화면이 없어서 다음처럼 멘트를 수정했습니다!
```ts
boldText: '현재 해당 카테고리에 등록된 서비스가 없습니다.',
subText: '다른 카테고리를 확인해보세요!',
```
(PROVIDER가 알고보니 카테고리 없을 때 나타내는 emptyscreen이더라구요..? 뒤늦게 알았지만 이참에 멘트 한번 더 수정하는 것도 나쁘지 않을 것 같아 수정했습니당)
> fix: 랭킹 카테고리 결과 없는 경우 아무것도 안뜨는 상태

- src/utils/formatDateTime.ts
- #297
`formatDateTime` 함수 내에 불필요한 `+1`을 삭제했습니다
히스토리 추적해보니까 [초반 커밋](https://github.com/yourssu/Soomsil-Web/pull/85/commits/882dbeb5103ed4e8109ecb043899905554a8ac34)에는 day/hour/minute에 `+1`이 없는데 [유틸로 분리](https://github.com/yourssu/Soomsil-Web/pull/85/commits/5b7490bfacd6543ea6205087a39ece851375b39f)하면서 생겼더라고요
잘못 붙어있는 게 맞는 거 같아 지웠습니다
| before | after |
|:---:|:---:|
|![image](https://github.com/user-attachments/assets/55d23a4a-9e2a-4e1e-b8e0-ca1275cff6e5)|![image](https://github.com/user-attachments/assets/b0a588b0-6a79-4d4b-bf6f-44e8ea86df5a)|
앱과 날짜 형식이 다른 문제는 앱 형식으로 통일했습니다 ([관련 스레드](https://yourssu.slack.com/archives/C0661SMJ8DQ/p1725273062180819))
> fix: formatDateTime에서 시간이 제대로 변환되지 않는 문제

- src/home/components/SignupContents/EmailAuth/useEmailAuth.ts
- resolved #307 
- #299 에서 10초로 변경되었던 학교 메일 인증 시간을 8분으로 변경하였습니다.
> fix: 메일 인증 시간 10초 -> 8분으로 변경
